version: "3.9"

services:


  postgres-db:
    image: postgres:15.5-alpine
    container_name: postgres-db
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=healenium
      - POSTGRES_USER=healenium_user
      - POSTGRES_PASSWORD=${DB_PWD}
    networks:
      - healenium
   
  healenium:
    image: healenium/hlm-backend:3.4.4
    container_name: healenium
    restart: on-failure
    ports:
      - "7000:7878"
    environment:
      - SPRING_POSTGRES_DB=healenium
      - SPRING_POSTGRES_SCHEMA=healenium
      - SPRING_POSTGRES_USER=healenium_user
      - SPRING_POSTGRES_PASSWORD=${DB_PWD}
      - SPRING_POSTGRES_DB_HOST=postgres-db
      - KEY_SELECTOR_URL=false
      - COLLECT_METRICS=true
      - HLM_LOG_LEVEL=debug
    volumes:
      - ./screenshots/:/screenshots
      - ./logs/:/logs
    env_file:
          - ./default.env
    networks:
      - healenium

  selector-imitator:
    image: healenium/hlm-selector-imitator:1.4
    container_name: selector-imitator
    restart: on-failure
    ports:
      - "8001:8000"
    networks:
      - healenium

networks:
  healenium:
    name: healenium
