version: "3.9"

services:

       
  healenium:
    image: healenium/hlm-backend:3.4.6
    container_name: healenium
    restart: on-failure
    ports:
      - "7878:7878"
    environment:
      - SPRING_POSTGRES_DB=dashboard
      - SPRING_POSTGRES_SCHEMA=healenium
      - SPRING_POSTGRES_USER=healeniumusr
      - SPRING_POSTGRES_PASSWORD=/run/secrets/db_pwd
      - SPRING_POSTGRES_DB_HOST=cx-engineering-dashboard.cluster-c2wox3myqpsn.us-east-1.rds.amazonaws.com
      - KEY_SELECTOR_URL=false
      - COLLECT_METRICS=true
      - HLM_LOG_LEVEL=debug
    volumes:
      - ./screenshots/:/screenshots
      - ./logs/:/logs
    networks:
      - healenium
    secrets:
       - db_pwd

  selector-imitator:
    image: healenium/hlm-selector-imitator:1.4
    container_name: selector-imitator
    restart: on-failure
    ports:
      - "8000:8000"
    networks:
      - healenium
secrets:
   db_pwd:
     file: db_pwd.txt
networks:
  healenium:
    name: healenium
