version: "3.9"

services:

  healenium:
    image: healenium/hlm-backend:3.4.4
    container_name: healenium
    restart: on-failure
    ports:
      - "7878:7878"
    environment:
      - SPRING_POSTGRES_DB=healenium
      - SPRING_POSTGRES_SCHEMA=healenium
      - SPRING_POSTGRES_USER=healenium_user
      - SPRING_POSTGRES_PASSWORD=YDk2nmNs4s9aCP6O
      - SPRING_POSTGRES_DB_HOST=db-healenium-cluster.cluster-czqesgwywa8i.us-east-1.rds.amazonaws.com
      - KEY_SELECTOR_URL=false
      - COLLECT_METRICS=false
      - HLM_LOG_LEVEL=debug
    volumes:
      - ./screenshots/:/screenshots
      - ./logs/:/logs
    networks:
      - healenium

  selector-imitator:
    image: healenium/hlm-selector-imitator:1.4
    container_name: selector-imitator
    restart: on-failure
    ports:
      - "8000:8000"
    networks:
      - healenium

networks:
  healenium:
    name: healenium
